server:
  port: 7900
spring:
  application:
    name: microservice-zhilong-provider-user-v1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.ncs: DEBUG
eureka:
  client:
    healthcheck:
      enabled: false #true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka #http://peer1:8761/eureka,http://peer2:8762/eureka 
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    #appname: USER-SERVICE-HAHA
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java: 
      source: @java.version@
      target: @java.version@