server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhilonglee/config-repo
          username: 
          password: 
  application:
    name: microservice-zhilong-config-server-eureka
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true