server:
  port: 8010
  context-path: /ribbon
spring:
  application:
    name: microservice-zhilong-movie-ribbon-with-hystrix
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    home-page-url-path: /ribbon
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}