security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhilonglee/config-repo
          username: 
          password:
encrypt:
  key: foo
          
