server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhilonglee/config-repo
          username:
          password:
          force-pull: true
encrypt:
  key: foo