server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhilonglee/config-repo
          repos:
            simple: https://github.com/zhilonglee/simple
            special:
              pattern: special*/dev*,special*/test*
              uri: https://github.com/zhilonglee/special